### PR TITLE
Add website classification

### PR DESCRIPTION
**Pull request by octopusinvitro**
This PR allows **website user names** (like those for services like Facebook, Flickr, YouTube, etc.) that are read from a person's Wikidata page to be stored in the Popolo file as identifiers.

In our way there, we also refactored some smelly code and simplified complex methods
## Notes to reviewer:
- A new VCR cassette was loaded for [Konstantinos Mitsotakis](https://www.wikidata.org/wiki/Special:EntityData/Q866.json), since he has two **website user names**: YouTube and Flickr.
- The [P553](https://www.wikidata.org/w/index.php?title=Property_talk:P553&oldid=383992678) id in Wikidata refers to websites, which is the field from where we are reading the website user names. We are using it in the code to fetch the websites information.
- The **website user names** have an id of [P554](https://www.wikidata.org/wiki/Property_talk:P554) that is mandatory (will always be present if P553 is present), so we are hardcoding it safely but adding a `rescue` just in case.

Closes https://github.com/everypolitician/everypolitician/issues/519

### CODE REVIEW

**Comment by crocodileDundee** [comment]
@tmtmtmtm what's the error, could you copy-paste it please. Sounds like it can potentially be an easy fix :slightly_smiling_face:

**Comment by octopusinvitro** [comment]
@tmtmtmtm what's the error, could you copy paste it please. Sounds like it could potentially be an easy fix

**Comment by tmtmtmtm** [comment]
```ruby
sqlite3-1.3.11/lib/sqlite3/database.rb:91:in `initialize': near "world": syntax error (SQLite3::SQLException)
```

(you can test this by running that scraper yourself locally with the Gemfile changed to point at this branch)

**Comment by tmtmtmtm** [comment]
This version failed quite nastily when the site name was something like `My World@Mail.Ru`. Superseded by https://github.com/everypolitician/wikidata-fetcher/pull/51

**Pull request closed without merging**
